/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_northmeter_meshble_jnjutils_JniUtilsECDH */

#ifndef _Included_com_northmeter_meshble_jnjutils_JniUtilsECDH
#define _Included_com_northmeter_meshble_jnjutils_JniUtilsECDH
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_northmeter_meshble_jnjutils_JniUtilsECDH
 * Method:    getString
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_northmeter_meshble_jnjutils_JniUtilsECDH_getString
  (JNIEnv *, jobject);

/*
 * Class:     com_northmeter_meshble_jnjutils_JniUtilsECDH
 * Method:    add
 * Signature: (II)I
 */
JNIEXPORT jint JNICALL Java_com_northmeter_meshble_jnjutils_JniUtilsECDH_add
  (JNIEnv *, jobject, jint, jint);

/*
 * Class:     com_northmeter_meshble_jnjutils_JniUtilsECDH
 * Method:    makeKey
 * Signature: ()[B
 */
JNIEXPORT jbyteArray JNICALL Java_com_northmeter_meshble_jnjutils_JniUtilsECDH_makeKey
  (JNIEnv *, jobject);

/*
 * Class:     com_northmeter_meshble_jnjutils_JniUtilsECDH
 * Method:    sharedSecret
 * Signature: ([B[B)[B
 */
JNIEXPORT jbyteArray JNICALL Java_com_northmeter_meshble_jnjutils_JniUtilsECDH_sharedSecret
  (JNIEnv *, jobject, jbyteArray, jbyteArray);

#ifdef __cplusplus
}
#endif
#endif
