/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_northmeter_meshble_jnjutils_JniUtilsST */

#ifndef _Included_com_northmeter_meshble_jnjutils_JniUtilsST
#define _Included_com_northmeter_meshble_jnjutils_JniUtilsST
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_northmeter_meshble_jnjutils_JniUtilsST
 * Method:    securityAesCMAC
 * Signature: ([B[B)[B
 */
JNIEXPORT jbyteArray JNICALL Java_com_northmeter_meshble_jnjutils_JniUtilsST_securityAesCMAC
  (JNIEnv *, jobject, jbyteArray, jbyteArray);

/*
 * Class:     com_northmeter_meshble_jnjutils_JniUtilsST
 * Method:    securityKSaltGeneration
 * Signature: ([B)[B
 */
JNIEXPORT jbyteArray JNICALL Java_com_northmeter_meshble_jnjutils_JniUtilsST_securityKSaltGeneration
  (JNIEnv *, jobject, jbyteArray);

/*
 * Class:     com_northmeter_meshble_jnjutils_JniUtilsST
 * Method:    securityK1derivation
 * Signature: ([B[B[B)[B
 */
JNIEXPORT jbyteArray JNICALL Java_com_northmeter_meshble_jnjutils_JniUtilsST_securityK1derivation
  (JNIEnv *, jobject, jbyteArray, jbyteArray, jbyteArray);

/*
 * Class:     com_northmeter_meshble_jnjutils_JniUtilsST
 * Method:    securityK2derivation
 * Signature: ([B[B)[B
 */
JNIEXPORT jbyteArray JNICALL Java_com_northmeter_meshble_jnjutils_JniUtilsST_securityK2derivation
  (JNIEnv *, jobject, jbyteArray, jbyteArray);

/*
 * Class:     com_northmeter_meshble_jnjutils_JniUtilsST
 * Method:    securityK3derivation
 * Signature: ([B)[B
 */
JNIEXPORT jbyteArray JNICALL Java_com_northmeter_meshble_jnjutils_JniUtilsST_securityK3derivation
  (JNIEnv *, jobject, jbyteArray);

/*
 * Class:     com_northmeter_meshble_jnjutils_JniUtilsST
 * Method:    securityK4derivation
 * Signature: ([B)[B
 */
JNIEXPORT jbyteArray JNICALL Java_com_northmeter_meshble_jnjutils_JniUtilsST_securityK4derivation
  (JNIEnv *, jobject, jbyteArray);

/*
 * Class:     com_northmeter_meshble_jnjutils_JniUtilsST
 * Method:    securityAesCcmEncrypt2
 * Signature: ([B[B[BBB)[B
 */
JNIEXPORT jbyteArray JNICALL Java_com_northmeter_meshble_jnjutils_JniUtilsST_securityAesCcmEncrypt2
  (JNIEnv *, jobject, jbyteArray, jbyteArray, jbyteArray, jbyte, jbyte);

/*
 * Class:     com_northmeter_meshble_jnjutils_JniUtilsST
 * Method:    securityAesCcmDecrypt2
 * Signature: ([B[B[BBB)[B
 */
JNIEXPORT jbyteArray JNICALL Java_com_northmeter_meshble_jnjutils_JniUtilsST_securityAesCcmDecrypt2
  (JNIEnv *, jobject, jbyteArray, jbyteArray, jbyteArray, jbyte, jbyte);

#ifdef __cplusplus
}
#endif
#endif
